from __future__ import annotations

import asyncpg
from fastapi import APIRouter, Depends, HTTPException, Query, status

from app.api.deps import get_postgres_connection
from app.api.schemas.synthesis import (
    SynthesisPackageResponse,
    SynthesisValidationRequest,
    SynthesisValidationResponse,
)
from app.search.evidence import search_evidence
from app.search.evidence_bundle import build_evidence_bundle_payload
from app.synthesis.contract import build_synthesis_package, validate_synthesis_draft

router = APIRouter(tags=["synthesis"])


@router.get(
    "/synthesis-package",
    response_model=SynthesisPackageResponse,
    summary="Prepare a citation-constrained synthesis package",
    description=(
        "Builds an evidence bundle from PostgreSQL-hydrated semantic evidence and "
        "wraps it in a provider-neutral LLM contract. No model is called and no "
        "answer is generated by this endpoint."
    ),
)
async def synthesis_package(
    q: str = Query(..., min_length=1, max_length=500),
    limit: int = Query(5, ge=1, le=20),
    work_uri: str | None = Query(None, max_length=255),
    include_rejected: bool = Query(False),
    conn: asyncpg.Connection = Depends(get_postgres_connection),
) -> SynthesisPackageResponse:
    query = q.strip()
    if not query:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Synthesis question must contain non-whitespace characters",
        )

    try:
        analysis, query_variants, results = await search_evidence(
            conn,
            query,
            limit=limit,
            work_uri=work_uri,
            include_rejected=include_rejected,
        )
        bundle = build_evidence_bundle_payload(analysis, query_variants, results)
        package = build_synthesis_package(bundle)
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Synthesis evidence retrieval is unavailable, stale, or inconsistent",
        ) from exc
    except asyncpg.PostgresError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Synthesis evidence storage is temporarily unavailable",
        ) from exc

    return SynthesisPackageResponse.model_validate(package)


@router.post(
    "/validate-synthesis",
    response_model=SynthesisValidationResponse,
    summary="Validate citation mechanics for a synthesis draft",
    description=(
        "Checks package integrity, allowed citation ids, and whether ANSWERED claims "
        "are structurally cited. It does not yet judge whether each source actually "
        "entails the claim."
    ),
)
async def validate_synthesis(
    request: SynthesisValidationRequest,
) -> SynthesisValidationResponse:
    result = validate_synthesis_draft(
        request.package.model_dump(),
        request.draft.model_dump(),
    )
    return SynthesisValidationResponse.model_validate(result)
